### ISSUE TITLE
Graph batch in your code.

### ISSUE THREAD

**Issue by Lee-zix** [toooooodo/CompGCN-DGL#2]
Dear author,
     In the example of R-GCN in DGL, they use edge neighborhood sampling strategy to reduce the memory cost. It seems that the whole graph is taken as the input of CompGCN layer in your code.   I wonder whether the code is computationally prohibitive and demands hefty memory footprints if the scalability of the input graph gets lager. Do you have some ideas with this problem or do I have some misunderstanding with your code?
Looking forward for your reply!

**Comment by toooooodo** [comment]
Hi, parameters in CompGCN are less than R-GCN, so memory footprints occupied by CompGCN is less than R-GCN on the same dataset. And on the same GPU, maybe it need to samples edges to train R-GCN but the whole graph can be put into GPU when you train CompGCN. Also, as you see,  a large graph is really a challange for training process of all the GNN model.  DGL provides some sampling API, it maybe alleviate this problem.

**Comment by Lee-zix** [comment]
Thanks very much for your timely reply! It helps a lot!
